### ISSUE TITLE
MD5 checksum issue

### ISSUE THREAD

**Issue by JeremyEnns** [conda-forge/marshmallow-feedstock#7]
It appears that one of the packages uploaded to the conda-forge channel on anaconda.org has an incorrect md5 checksum.

Actual:

   $ openssl md5 linux-64-marshmallow-2.10.4-py27_0.tar.bz2 
MD5(linux-64-marshmallow-2.10.4-py27_0.tar.bz2)= cb322a9e1f0840c281e2230fd07e704f

Listed:

<img width="735" alt="screen shot 2017-01-18 at 5 08 32 pm" src="https://cloud.githubusercontent.com/assets/11463175/22087045/6a060474-dda1-11e6-8709-76b5078f3b7b.png">

**Comment by hajapy** [comment]
@JeremyEnns Yes, I am aware of this issue. We could probably use someone from @conda-forge/core  to look into it and remove the bad build or mark it as broken. There is a higher priority build that should mitigate the issue.

If you look at https://circleci.com/gh/conda-forge/marshmallow-feedstock/tree/master, it looks like the merge for 2.10.4 launched 3 circleci builds (28, 29, 30). 

BTW, to make the higher priority build, I bumped the build number and saw 3 circleci builds triggered by the merge to develop. I had to manually cancel 2 of them to prevent the issue from repeating itself. My hunch is that this feedstock got registered multiple times with circleci, but unfortunately I have no way to checking or fixing that.

**Comment by rth** [comment]
> My hunch is that this feedstock got registered multiple times with circleci, but unfortunately I have no way to checking or fixing that.

@hajapy Yes, I got 3 emails notifying  for subscription notifications from Circle CI when I made a PR to this repo. For other feedstoks, I receive just one...

**Comment by hajapy** [comment]
Can someone form @conda-forge/core please have a look at this? It shouldn't take long to sort out.

**Comment by jakirkham** [comment]
Actually it gets weirder. Turns out that there are two packages with identical name and version number. One of them has no downloads and has the "wrong" checksum. The other has all of the downloads and has the "right" checksum. Why there are two packages with an identical name is a very interesting question. Would recommend raising an issue with the Anaconda team on their [issue tracker]( https://github.com/Anaconda-Platform/support/issues ).

<img width="1552" alt="screen shot 2017-02-06 at 11 31 16" src="https://cloud.githubusercontent.com/assets/3019665/22655959/cbf5f5aa-ec5f-11e6-983b-0aa578be96c5.png">

**Comment by jakirkham** [comment]
Also found two extra CircleCI webhooks. Have removed them so there is only one. It is possible these two uploads occurred at the same time and somehow they were both allowed in. This is ultimately related to a known CI registration issue.

xref: https://github.com/conda-forge/conda-smithy/issues/444

**Comment by rth** [comment]
Closing as fixed (if I didn't miss anything). Thanks @jakirkham !
